title: Pedro's Digital Garden
remote_theme: pmarsceill/just-the-docs

# Ativa o Dark Mode nativo
color_scheme: dark

# Configuração crítica para não bugar o LaTeX
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  # Isso evita que o kramdown tente processar o que está dentro de blocos matemáticos
  parse_block_html: true
  commonmark:
    hard_line_breaks: false